<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;

class Organization extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'organization_id',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Organization $organization) {
            $organization->slug = Str::uuid()->toString();
        });
    }

    public function zohoConfig(): HasOne
    {
        return $this->hasOne(ZohoConfig::class, 'organization_id');
    }

    // TODO Scope
    #[Scope]
    protected function filter(Builder $query, $request): Builder
    {
        $search = $request['search'] ?? null;

        return $query->when($search, fn($query) => $query->whereLike('name', '%' . $search . '%'));
    }
}
